apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app: api-server
data:
  PORT: "8080"
  ENVIRONMENT: "development"
  VERSION: "dev"
  DB_HOST: "host.docker.internal"
  DB_PORT: "3306"
  DB_USER: "root"
  DB_PASS: "root"
  DB_NAME: "app"
  MEMCACHED_HOST: "host.docker.internal"
  MEMCACHED_PORT: "11211"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  DEBUG_LOGGING: "true" 