apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-server
  labels:
    app: worker-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-server
  template:
    metadata:
      labels:
        app: worker-server
    spec:
      containers:
      - name: worker-server
        image: worker-server:latest 