apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  labels:
    app: worker-server
data:
  PORT: "8081"
  ENVIRONMENT: "development"
  VERSION: "dev"
  SCHEDULER_INTERVAL: "1"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "root"
  MYSQL_DATABASE: "app"
  MEMCACHED_HOST: "memcached"
  MEMCACHED_PORT: "11211"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest" 