apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-server
  labels:
    app: worker-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-server
  template:
    metadata:
      labels:
        app: worker-server
    spec:
      containers:
      - name: worker-server
        image: worker-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: worker-config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: worker-server
spec:
  selector:
    app: worker-server
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP 