# Development stage
FROM golang:1.23

WORKDIR /app

# Install necessary build tools
RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

# Copy go mod files from the root of the build context to the WORKDIR
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the internal package from the root of the build context
COPY internal/ ./internal/

# Copy the source code for this service
COPY api/. ./api/

# Expose port
EXPOSE 8080

# O entrypoint será definido pelo Tilt/restart_process
# CMD ["go", "run", "main.go"] 